[project]
name = "integrations_sdk"
version = "0.1.0"
description = ""
authors = [
    {name = "Fabian",email = "fabian@sorqvist.nu"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard] (>=0.115.12,<0.116.0)",
    "black (>=25.1.0,<26.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pytest (>=8.4.0,<9.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "typer (>=0.16.0,<0.17.0)",
    "responses (>=0.25.8,<0.26.0)",
    "jsonschema (>=4.25.1,<5.0.0)",
    "ruff>=0.13.3",
    "pyright>=1.1.406",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/ebbot-ai/challenger-sdk"
"Bug Tracker" = "https://github.com/ebbot-ai/challenger-sdk"

[tool.poetry.scripts]
integrations = "integrations_sdk.cli:app"
